name: Apply /apply patch
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    if: startsWith(github.event.comment.body, '/apply ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Extract title and diff
        id: extract
        env:
          BODY: ${{ github.event.comment.body }}
        run: |
          TITLE="$(printf "%s" "$BODY" | head -n1 | sed -E 's#^/apply[[:space:]]*##')"
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          # Берём первый блок ```diff ... ```
          awk '
            tolower($0) ~ /^```[[:space:]]*diff[[:space:]]*$/ && !in {in=1; next}
            /^```/ && in {in=0; exit}
            in {print}
          ' <<< "$BODY" > patch.diff
          test -s patch.diff || { echo "No diff block found"; exit 1; }
          head -n 20 patch.diff

      - name: Apply and commit
        run: |
          set -euxo pipefail
          BR="chatgpt/apply-${{ github.event.comment.id }}"
          git switch -c "$BR"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git apply --check --whitespace=fix patch.diff
          git apply --whitespace=fix patch.diff
          git add -A
          git commit -m "${{ steps.extract.outputs.title }}"

      - name: Open draft PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: ${{ steps.extract.outputs.title }}
          commit-message: ${{ steps.extract.outputs.title }}
          branch: chatgpt/apply-${{ github.event.comment.id }}
          base: main
          draft: true
          body: Automated from ${{ github.event.comment.html_url }}
