name: Apply files from comment (robust)

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply-files:
    if: startsWith(github.event.comment.body, '/apply-files ')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Parse comment and write files
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const body = context.payload.comment.body;
            // Find fenced blocks like ```file:relative/path\n<content>\n```
            const re = /```file:([\w\-./]+)\n([\s\S]*?)```/g;
            let match;
            let written = [];
            while ((match = re.exec(body)) !== null) {
              const rel = match[1].trim();
              const content = match[2].replace(/\r\n/g, "\n"); // normalize newlines
              if (rel.includes('..')) {
                core.setFailed(`Refusing to write outside repo: ${rel}`);
                process.exit(1);
              }
              const abs = path.join(process.cwd(), rel);
              fs.mkdirSync(path.dirname(abs), { recursive: true });
              fs.writeFileSync(abs, content, 'utf8');
              written.push(rel);
            }
            if (written.length === 0) {
              core.setFailed('No ```file:<path>``` blocks found in comment.');
              process.exit(1);
            }
            core.setOutput('written', JSON.stringify(written));

      - name: Commit & push
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            title="$(echo "${{ github.event.comment.body }}" | head -n1 | sed 's|/apply-files ||')"
            if [ -z "$title" ]; then title="apply-files"; fi
            git commit -m "apply-files: $title"
            git push
          else
            echo "No changes to commit."

      - name: Report back
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const written = core.getInput('written') || '[]';
            const files = JSON.parse(written);
            const msg = files.length 
              ? `✅ Applied files: \n\n- ${files.join('\n- ')}`
              : `⚠️ No files applied.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue ? context.payload.issue.number : context.payload.comment.issue_url.split('/').pop(),
              body: msg
            });
