name: Apply files from comment (robust v3)

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write

jobs:
  apply-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Parse comment and write files
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const body = context.payload.comment.body || '';
            // Only act if the comment begins with /apply-files (allow optional leading spaces/newline)
            const trimmed = body.replace(/^\s+/, '');
            if (!trimmed.startsWith('/apply-files')) {
              core.notice('No /apply-files command found; skipping.');
              core.setOutput('written', '');
              return;
            }
            // Find fenced blocks like ```file:relative/path\n<content>\n```
            const re = /```file:([\w\-./]+)\n([\s\S]*?)```/g;
            let match;
            let written = [];
            while ((match = re.exec(body)) !== null) {
              const rel = match[1].trim();
              const content = match[2].replace(/\r\n/g, "\n"); // normalize newlines
              if (rel.includes('..')) {
                core.setFailed(`Refusing to write outside repo: ${rel}`);
                return;
              }
              const abs = path.join(process.cwd(), rel);
              fs.mkdirSync(path.dirname(abs), { recursive: true });
              fs.writeFileSync(abs, content, 'utf8');
              written.push(rel);
            }
            core.setOutput('written', written.join('\n'));

      - name: Commit & push (if any changes)
        if: steps.parse.outputs.written != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          title="$(echo "${{ github.event.comment.body }}" | head -n1 | sed 's|/apply-files *||')"
          if [ -z "$title" ]; then title="apply-files"; fi
          git commit -m "apply-files: $title"
          git push

      - name: Summary
        run: |
          echo "Written files (if any):"
          echo "${{ steps.parse.outputs.written }}"

