name: Apply /apply-main to default branch

on:
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: write
  pull-requests: write

jobs:
  apply-main:
    # Запускаем джоб только если первый ряд комментария начинается с /apply-main
    if: ${{ startsWith(github.event.comment.body, '/apply-main') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract title and diff from comment
        id: extract
        shell: bash
        env:
          BODY: ${{ github.event.comment.body }}
        run: |
          set -e
          # Заголовок коммита = всё после "/apply-main "
          title="$(printf "%s" "$BODY" | head -n1 | sed -E 's#^/apply-main[[:space:]]*##')"
          printf 'title=%s\n' "$title" >> "$GITHUB_OUTPUT"

          # Вырезаем ПЕРВЫЙ блок с ```diff ... ```
          awk '
            tolower($0) ~ /^```[[:space:]]*diff[[:space:]]*$/ && !inside { inside=1; next }
            /^```/ && inside { inside=0; exit }
            inside { print }
          ' <<< "$BODY" > patch.diff

          # Проверка, что diff есть
          test -s patch.diff || { echo "No diff block found"; exit 1; }

          echo "Preview:"
          head -n 20 patch.diff || true

      - name: Apply patch and push to default branch
        shell: bash
        env:
          DEFAULT: ${{ github.event.repository.default_branch }}
          TITLE:   ${{ steps.extract.outputs.title }}
        run: |
          set -euxo pipefail
          # Готовим main (или другой дефолт)
          git fetch origin "$DEFAULT"
          git checkout -B "$DEFAULT" "origin/$DEFAULT" || git checkout "$DEFAULT"

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Пробуем применить diff
          git apply --check --whitespace=fix patch.diff
          git apply --whitespace=fix patch.diff

          git add -A
          git commit -m "${TITLE:-apply patch from /apply-main}"
          git push origin "HEAD:$DEFAULT"
